fos_rest:
  view:
    formats: { json: true, xml: false, rss: false, html: false }

  serializer:
    serialize_null: true

  param_fetcher_listener: true

  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: validationErrors
