fos_rest:
  view:
    formats:
      json: true
    view_response_listener: 'force'

  serializer:
    serialize_null: true

  param_fetcher_listener:
    enabled: true
    force: true

  format_listener:
    rules:
      - { path: ^/, priorities: [ json ], fallback_format: json, prefer_extension: true }

  body_listener: true

  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: validationErrors
