nelmio_api_doc:
    documentation:
        servers:
            - url: http://localhost:8000/
        info:
            title: Bilemo
            description: Just buy a goddamn phone !
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/api(?!/doc)
