@startuml
left to right direction

class User {
    string mail
    string name
    datetime registered_at
}

class Client {
    string name
    string password
}

class Product {
    string name
    string descr
    float price
		json tech_specs
}

Client  "1"--"n" User :has

@enduml
