@startuml
left to right direction
:Client:
package API {
		Client -- (List Products)
		Client -- (Detail Product)
    Client -- (List his own Users)
    Client -- (Detail one of his Users)
    Client -- (Add a new User linked to him)
    Client -- (Delete one of his Users)
}
@enduml
